_target_: lightning.pytorch.Trainer
accelerator: cpu
devices: 1
max_epochs: 3
log_every_n_steps: 10
deterministic: true
num_sanity_val_steps: 0
fast_dev_run: false
overfit_batches: 0.0
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
enable_checkpointing: true
enable_model_summary: true
logger: false
default_root_dir: outputs
